---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache2 package httpd
    yum:
      name: httpd
      state: absent
    
  - name: add php support for httpd apache
    yum:
      name: php
      state: absent

          
           

